# Generated by Django 4.2.1 on 2024-01-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='home/img')),
                ('status', models.CharField(choices=[('OV', 'Organic Vegetables'), ('OF', 'Organic Fruits')], default='OF', max_length=2)),
            ],
        ),
    ]
