# Generated by Django 4.2.1 on 2024-01-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselhome',
            name='img',
            field=models.ImageField(upload_to='home/'),
        ),
    ]
