# Generated by Django 4.2.1 on 2024-01-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_carouselhome_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('desigination', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='farmer/img')),
                ('slug', models.SlugField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='CarouselHome',
        ),
    ]
